# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44ec739de0f1ed8e63b0f17fe4b55908ebfa074eed630c8c13ccc2aa104c9c5cbeca300f36ae828eb77c6debbae0e09324871b39dbd347be307235fc478e307e

test:
  secret_key_base: e86c2effecb53771512723f36c69fbab92ee05e291145f488fa482f07a1043dcfef0dad0c1fe5b55b4adb5f288c2c2b00e3db1ed28cc7576982072432a3e9811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
